"""migration_2

Revision ID: 5c5bfec9db83
Revises: a32898f61699
Create Date: 2026-03-09 15:46:26.539684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5bfec9db83'
down_revision: Union[str, Sequence[str], None] = 'a32898f61699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'compensation',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resumes', 'compensation',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
